version: '2.14'
services:
  db-mongo:
    image: mongo
    container_name: db_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis

  app:
    build: .
    container_name: python_app
    volumes: 
      - .:/data
    ports:
      - '3000:3000'
    depends_on:
      - db-mongo


