name: metabase - Integracao Continua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Container up
        run: docker-compose up
        
  
  test:
  
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Install python and pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest-cov
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov
        
  
  docs:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install python and pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.12'
        
    - name: Install sphinx, doxygen and breathe
      run: |
        sudo apt install doxygen
        pip install breathe
        pip install -U sphinx
        
    - name: Run doxygen
    - uses: actions/checkout@v3
    - uses: mattnotmitt/doxygen-action@v1.9.5
      
      


